import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font.normal]
family = "Hack Nerd Font"

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.75
startup_mode = "SimpleFullscreen"

[font]
size = 16
